import { MetricComparison, PricingTier, ServiceItem, Testimonial } from './types';

export const BRAND_INFO = {
  name: 'DCOLLABERZ',
  tagline: 'Connect | Create | Grow',
  subheading: 'Turn Attention Into Measurable Growth',
  description: 'Digital marketing that turns your online presence into measurable business growth. We help businesses in Krishnagiri, Hosur, Dharmapuri & across Tamil Nadu dominate local searches, generate qualified WhatsApp leads, and scale revenue.',
  officialEmail: 'dcollaberzoffical@gmail.com',
  adminEmail: 'hariharanrobo123@gmail.com',
  whatsappNumber: '+919363130071',
  whatsappDisplay: '+91 93631 30071',
  contactPhone: '+91 74020 58614',
  contactPhoneRaw: '7402058614',
  location: 'Krishnagiri, Tamil Nadu, India',
  serviceAreas: ['Krishnagiri', 'Hosur', 'Dharmapuri', 'Kaveripattinam', 'Bargur', 'Rayakottai', 'Bengaluru South Border'],
  populationReach: '2.45 Million',
  estimatedLocalLeads: '24,500+ Qualified Leads',
};

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'tier-1-silver',
    name: 'Silver Starter',
    subtitle: 'Foundation for Local Online Presence',
    tierNumber: 'Tier-1',
    priceMonthly: 25999,
    priceQuarterly: 22099, // 15% discount for 3 months
    features: [
      '4–5 Posts / Month (2 Key Platforms)',
      '3 High-Engagement Reels',
      '3 Trending YouTube/Insta Shorts',
      'Professional Content Creation & Scripting',
      'On-Location Model / Store Shoot',
      'End-to-End Social Media Management',
      'Dedicated Email & Support Desk',
      'Google Business Profile Basic Optimization',
      'Monthly Growth Summary Report',
    ],
    recommendedFor: 'Small local stores, cafes, clinics, & independent service providers starting out.',
    color: 'emerald',
  },
  {
    id: 'tier-2-gold',
    name: 'Gold Growth Lead',
    badge: 'MOST POPULAR',
    subtitle: 'High Velocity Lead Generation & Website',
    tierNumber: 'Tier-2',
    priceMonthly: 50000,
    priceQuarterly: 42500, // 15% discount
    popular: true,
    features: [
      '10 High-Impact Posts / Month (3 Platforms)',
      '6 Cinematic Reels with Professional Audio',
      '6 Viral-Formatted Shorts',
      'Quality Studio Content Creation & Copy',
      '2 Active Meta (FB & Instagram) Ad Campaigns',
      'High-Converting Custom Business Website / Landing Page',
      'Live Analytics & ROI Dashboard (Power BI / Web)',
      'Monthly 1-on-1 Strategic Growth Session',
      'WhatsApp Lead Capture Funnel Setup',
      'Google Maps / Local SEO Rank Tracking',
    ],
    recommendedFor: 'Established restaurants, specialty hospitals, multi-brand showrooms, and expanding businesses.',
    color: 'amber',
  },
  {
    id: 'tier-3-diamond',
    name: 'Diamond Full Performance',
    badge: 'SCALE TO MARKET LEADER',
    subtitle: 'Omnichannel Dominance & Dedicated Strategy Lead',
    tierNumber: 'Tier-3',
    priceMonthly: 75000,
    priceQuarterly: 63750,
    features: [
      '15+ Premium Posts / Month (4 Major Platforms)',
      '10 Cinematic 4K Reels + Hook Storytelling',
      '10 High-Retention Shorts',
      '4+ Advanced Meta & Google PPC Ad Campaigns',
      'Custom Full-Stack Business Web Platform + Fast Hosting',
      'Complete Local & Regional SEO Domination',
      'Omnichannel Email Support & Automated Email Marketing',
      'Dedicated Priority WhatsApp Business Support',
      'Real-Time Live KPI Dashboard with SQL/Power BI metrics',
      'Weekly In-Depth KPI Reports & Conversion Audits',
      'Dedicated Strategy Lead Assigned to Your Account',
      'Video Testimonial Production & Influencer Tie-ups',
    ],
    recommendedFor: 'Large real estate developers, educational institutions, hospital networks, and manufacturing firms.',
    color: 'cyan',
  },
];

export const GROWTH_METRICS: MetricComparison[] = [
  {
    label: 'Website Visitors',
    before: 120,
    after: 540,
    growth: '+350%',
    unit: 'Monthly Visitors',
    iconName: 'Users',
    description: 'Targeted visitors driven through Local SEO and Meta Campaigns.',
  },
  {
    label: 'Enquiries (Calls & WhatsApp)',
    before: 35,
    after: 210,
    growth: '+500%',
    unit: 'Qualified Enquiries',
    iconName: 'PhoneCall',
    description: 'High-intent phone calls and direct WhatsApp messaging leads.',
  },
  {
    label: 'Sales & Conversions',
    before: 22,
    after: 126,
    growth: '+473%',
    unit: 'Closed Customers',
    iconName: 'ShoppingBag',
    description: 'Paying customers converted from online discovery.',
  },
  {
    label: 'Social Media Reach',
    before: 800,
    after: 3600,
    growth: '+350%',
    unit: 'Targeted Impressions',
    iconName: 'Share2',
    description: 'Reaching genuine regional customers on Instagram & Facebook.',
  },
  {
    label: 'Google Business Views',
    before: 1200,
    after: 5800,
    growth: '+383%',
    unit: 'Local Searches & Map Views',
    iconName: 'MapPin',
    description: 'Customers finding your business first when searching in Krishnagiri.',
  },
];

export const PILLARS = [
  {
    number: '01',
    title: 'Reach More Customers',
    description: 'Digital marketing helps businesses reach a larger audience beyond their local area through Google, social media, websites, and online advertising.',
    icon: 'Globe',
    highlight: 'Expand Beyond Walk-ins',
  },
  {
    number: '02',
    title: 'Generate Quality Leads',
    description: 'Targeted campaigns help businesses reach people who are genuinely interested in their products or service.',
    icon: 'Target',
    highlight: 'High-Intent Buyers Only',
  },
  {
    number: '03',
    title: 'Build Brand Awareness',
    description: 'A strong online presence helps customers recognize, remember, and trust your brand above all local competitors.',
    icon: 'Sparkles',
    highlight: 'Top-of-Mind Recall',
  },
  {
    number: '04',
    title: 'Stay Ahead of Competitors',
    description: 'Customers are already searching online. Digital marketing helps businesses compete and stand out in a crowded market.',
    icon: 'TrendingUp',
    highlight: 'Rank #1 in Your Region',
  },
  {
    number: '05',
    title: 'Increase Sales & Revenue',
    description: 'Effective digital campaigns turn online visitors into leads and leads into paying repeat customers.',
    icon: 'BadgePercent',
    highlight: 'Measurable ROI',
  },
  {
    number: '06',
    title: 'Target the Right Audience',
    description: 'Businesses can target customers based on location, age, interests, behavior, and search intent.',
    icon: 'UserCheck',
    highlight: 'Zero Wasted Ad Spend',
  },
  {
    number: '07',
    title: 'Measure Marketing Performance',
    description: 'Unlike traditional banners and flyers, digital marketing allows businesses to track impressions, clicks, leads, conversions, cost per lead, and ROI.',
    icon: 'BarChart3',
    highlight: '100% Trackable Data',
  },
  {
    number: '08',
    title: 'Build Customer Relationships',
    description: 'Social media, WhatsApp, email, and content marketing help businesses communicate with customers and build long-term loyalty.',
    icon: 'HeartHandshake',
    highlight: 'Repeat Business Engine',
  },
  {
    number: '09',
    title: 'Live Dashboards & Analytics',
    description: 'Live Dashboards visualize the raw data of your clients, making it crystal clear to understand business demand and scale.',
    icon: 'LayoutDashboard',
    highlight: 'Power BI & SQL Reports',
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'social-media',
    title: 'Social Media Marketing',
    tagline: 'Instagram & Facebook Dominance',
    description: 'Strategic daily content, visual storytelling, community management, and paid boost sequences that turn followers into paying customers.',
    icon: 'Instagram',
    deliverables: ['Custom Brand Templates', 'Daily Story Engagements', 'Targeted Boost Campaigns', 'Community Direct Messaging Handling'],
    badge: 'Core Growth',
  },
  {
    id: 'local-seo',
    title: 'Google Business Profile & Local SEO',
    tagline: 'Get Found When Customers Search',
    description: 'Ensure your business appears in the coveted Google 3-Pack and Google Maps when customers in Krishnagiri search for your services.',
    icon: 'MapPin',
    deliverables: ['GMB Setup & Verification', 'Local Keyword Optimization', 'Customer Review Systems', 'Map Citation Authority'],
    badge: 'High Intent',
  },
  {
    id: 'google-ads',
    title: 'Google Search & PPC Ads',
    tagline: 'Instant High-Intent Lead Flow',
    description: 'Show up at the exact second a customer types "best restaurant in Krishnagiri" or "orthopedic doctor in Hosur". Pay only for real clicks.',
    icon: 'Search',
    deliverables: ['Search Keyword Bidding', 'Negative Keyword Shielding', 'Call-Only Ad Setup', 'Conversion Tracking Pixels'],
    badge: 'Immediate ROI',
  },
  {
    id: 'meta-ads',
    title: 'Meta Ads (Facebook & Instagram)',
    tagline: 'Precision Audience Retargeting',
    description: 'Hyper-targeted visual ads focusing on Krishnagiri, Hosur, Dharmapuri, and specific consumer interests with instant lead forms.',
    icon: 'Sliders',
    deliverables: ['Lead Generation Forms', 'Lookalike Audiences', 'Instagram Story & Reel Ads', 'Cost-Per-Lead Optimization'],
    badge: 'Mass Scale',
  },
  {
    id: 'web-landing',
    title: 'High-Converting Websites & Landing Pages',
    tagline: 'Turning Clicks into Calls',
    description: 'Lightning-fast, mobile-optimized business websites designed specifically to convert traffic into WhatsApp chats and booked appointments.',
    icon: 'Laptop',
    deliverables: ['3D Responsive Design', 'WhatsApp Instant Buttons', 'SEO Technical Architecture', 'Blazing Fast Speed'],
    badge: 'Digital Home',
  },
  {
    id: 'content-reels',
    title: 'Content & Viral Video Reels',
    tagline: 'Storytelling that Commands Attention',
    description: 'On-site shooting, model casting, high-grade 4K video editing, trending audio selection, and hook copywriting that stops the scroll.',
    icon: 'Video',
    deliverables: ['Scriptwriting & Hook Planning', 'Professional 4K Video Shoots', 'Subtitles & Motion Graphics', 'Trending Audio Research'],
    badge: 'Viral Reach',
  },
  {
    id: 'whatsapp-marketing',
    title: 'WhatsApp Direct Marketing & Automation',
    tagline: 'The #1 Communication Channel in Tamil Nadu',
    description: 'Automated welcome flows, catalog integrations, and broadcast nurturing that turn cold enquiries into warm, loyal customers.',
    icon: 'MessageSquare',
    deliverables: ['Official WhatsApp API Setup', 'Instant Automated Replies', 'Broadcast Promo Campaigns', 'Lead Tagging & Routing'],
    badge: 'Instant Response',
  },
];

export const PROBLEMS_VS_SOLUTIONS = [
  {
    problem: 'Low Online Visibility',
    problemDesc: 'Customers search online but cannot find your business.',
    solution: 'Dominant Local SEO & Google Business Profile ranking at the top.',
    impact: '+380% search impressions',
  },
  {
    problem: 'Competitors Appearing Before You',
    problemDesc: 'Competitors are grabbing customers searching on Google Maps.',
    solution: 'Hyper-targeted Google Search Ads and map citation blitz.',
    impact: 'Be the #1 choice in your town',
  },
  {
    problem: 'Few Enquiries From Online Channels',
    problemDesc: 'Spending money on flyers or random posts with zero leads.',
    solution: 'High-converting Landing Pages & 1-click WhatsApp lead funnels.',
    impact: '5x to 10x more phone & chat inquiries',
  },
  {
    problem: 'Poor Social Media Presence',
    problemDesc: 'Inconsistent posting, low-quality photos, and zero engagement.',
    solution: 'Cinematic 4K Reels, model shoots, and viral hook scripting.',
    impact: 'Build genuine authority & trust',
  },
  {
    problem: 'No Proper Lead Tracking',
    problemDesc: 'Not knowing which channel brought in actual paying customers.',
    solution: 'Live Power BI & SQL Dashboards visualizing cost-per-lead & ROI.',
    impact: '100% clarity on where every Rupee goes',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'S. Rajendran',
    role: 'Managing Director',
    company: 'Royal Spice Grand Restaurant & Banquet',
    location: 'Krishnagiri',
    category: 'Restaurant',
    rating: 5,
    comment: 'Before working with DCOLLABERZ, we relied purely on Highway pass-through traffic. Their Instagram Reels and Google Business Profile optimization boosted our weekend table bookings by over 400%. We now get continuous WhatsApp party enquiries daily!',
    result: '+420% Table Bookings & 210+ Monthly WhatsApp Enquiries',
    date: 'February 2026',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    verified: true,
  },
  {
    id: 't-2',
    name: 'Dr. K. Senthil Nathan, MS, MCh',
    role: 'Medical Director',
    company: 'Apex Multispeciality Hospital',
    location: 'Krishnagiri & Hosur',
    category: 'Hospital',
    rating: 5,
    comment: 'DCOLLABERZ established our hospital as the most trusted healthcare brand in Krishnagiri. Their Google Local SEO and patient awareness video shorts brought a massive increase in specialized outpatient appointments.',
    result: '+310% Outpatient Consultations & #1 Rank for Key Specialties',
    date: 'January 2026',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    verified: true,
  },
  {
    id: 't-3',
    name: 'V. Muruganandam',
    role: 'Founder & CEO',
    company: 'Green Valley Properties & Infra',
    location: 'Hosur - Krishnagiri Highway',
    category: 'Real Estate',
    rating: 5,
    comment: 'Meta ad campaigns designed by DCOLLABERZ generated over 140 high-intent site visit leads for our gated villa project within 45 days. The cost per qualified lead was 60% lower than previous agencies we tried.',
    result: '140+ Site Visit Leads & 18 Villa Plots Closed in 60 Days',
    date: 'January 2026',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    verified: true,
  },
  {
    id: 't-4',
    name: 'P. Anandhi',
    role: 'Proprietor',
    company: 'Sri Lakshmi Silks & Designer Studio',
    location: 'Krishnagiri Town',
    category: 'Showroom',
    rating: 5,
    comment: 'The model shoot and bridal collection reels created by the DCOLLABERZ crew went viral across Krishnagiri, Dharmapuri, and Tirupattur. Our festival footfall shattered all previous 5-year records!',
    result: '3.8x Festival Footfall & 85,000+ Organic Reel Views',
    date: 'December 2025',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    verified: true,
  },
  {
    id: 't-5',
    name: 'K. Balaji',
    role: 'Principal Correspondent',
    company: 'Vidya Vikas Matriculation School',
    location: 'Dharmapuri',
    category: 'School',
    rating: 5,
    comment: 'Their systematic 4-tier funnel for school admissions reached parents actively searching for quality education. The live dashboard gave our board complete visibility on admission inquiries and follow-ups.',
    result: '+185% Admission Enquiries for Academic Year 2026-27',
    date: 'January 2026',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    verified: true,
  },
  {
    id: 't-6',
    name: 'T. Shanmugam',
    role: 'Managing Partner',
    company: 'Precision Agro Components & Motors',
    location: 'Kaveripattinam Industrial Estate',
    category: 'Manufacturing',
    rating: 5,
    comment: 'B2B digital marketing was new to us, but DCOLLABERZ set up a professional website and Google Search campaign that landed us contracts from automotive tiers in Hosur and Chennai.',
    result: '8 High-Value B2B Contracts & Pan-Tamil Nadu Inquiries',
    date: 'February 2026',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    verified: true,
  },
];
